# Generated by Django 3.1.7 on 2021-03-07 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pub_title',
            new_name='pub_date',
        ),
    ]
